services:
  - type: web
    name: pravi-infra-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node src/server.js
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_EXPIRES_IN
        value: 1d
